cargo-features = ["profile-rustflags"]

[target.x86_64-unknown-linux-gnu]
#linker = "/usr/bin/clang"
#rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

[profile.perf]
inherits = "release"
lto = "fat"
#rustflags = ["-C", "-march=native"]
codegen-units = 1
opt-level = 3
debug = false

[profile.min]
inherits = "release"
lto = "thin"
#rustflags = ["-C", "-march=native"]
codegen-units = 1
opt-level = "s"
debug = false

[net]
git-fetch-with-cli = true

[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"
