#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width        10
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#4E5173"
bspc config focused_border_color "#ACB0D0"
bspc config active_border_color "#4E5173"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc pointer_modifier super

bspc config automatic_scheme spiral
bspc config initial_polarity second_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
