#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

BAR="$(xrdb -get bar)"
echo $BAR
case $(echo $BAR | tr '[:lower:]' '[:upper:]') in
"\"LEMONBAR\"") ~/.config/lemonbar/launch.sh & ;;
"\"POLYBAR\"") sh ~/.config/polybar/my/launch.sh >/dev/null ;;
esac

bspc monitor -d 1 2 3 4 5

bspc config border_width 5 #5
bspc config window_gap 10  #10

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "#FABD2F"
bspc config focused_border_color "#B8BB26"
bspc config active_border_color "#FB4934"

bspc config focus_follows_pointer true

bspc pointer_modifier super
bspc config pointer_follows_focus false

bspc config automatic_scheme spiral
bspc config initial_polarity second_child
