#!/bin/sh

export RESET='\e[0m'
export FG_BLACK='\e[30m'
export FG_RED='\e[31m'
export FG_GREEN='\e[32m'
export FG_YELLOW='\e[33m'
export FG_BLUE='\e[34m'
export FG_MAGENTA='\e[35m'
export FG_CYAN='\e[36m'
export FG_WHITE='\e[37m'
export BG_BLACK='\e[40m'
export BG_RED='\e[41m'
export BG_GREEN='\e[42m'
export BG_YELLOW='\e[43m'
export BG_BLUE='\e[44m'
export BG_MAGENTA='\e[45m'
export BG_CYAN='\e[46m'
export BG_WHITE='\e[47m'
