return {
	"ellisonleao/gruvbox.nvim",
	priority = 1000,
	config = function()
		require("vim").cmd([[ set cursorline ]])
		require("vim").o.background = "dark"
		require("gruvbox").setup({
			palette_overrides = {
				dark0 = "#1d2021",
				-- 	dark0_hard = "#1d2021",
				-- 	dark0 = "#1d2021",
				-- 	dark0_soft = "#1d2021",
				-- 	dark1 = "#1d2021",
				-- 	dark2 = "#1d2021",
				-- 	dark3 = "#1d2021",
				-- 	dark4 = "#1d2021",
				-- 	light0_hard = "#fbf1c7",
				-- 	light0 = "#fbf1c7",
				-- 	light0_soft = "#fbf1c7",
				-- 	light1 = "#fbf1c7",
				-- 	light2 = "#fbf1c7",
				-- 	light3 = "#fbf1c7",
				-- 	light4 = "#fbf1c7",
				-- 	bright_red = "#fb4934",
				-- 	bright_green = "#b8bb26",
				-- 	bright_yellow = "#fabd2f",
				-- 	bright_blue = "#83a598",
				-- 	bright_purple = "#d3869b",
				-- 	bright_aqua = "#8ec07c",
				-- 	bright_orange = "#fe8019",
				-- 	neutral_red = "#fb4934",
				-- 	neutral_green = "#b8bb26",
				-- 	neutral_yellow = "#fabd2f",
				-- 	neutral_blue = "#83a598",
				-- 	neutral_purple = "#d3869b",
				-- 	neutral_aqua = "#8ec07c",
				-- 	neutral_orange = "#fe8019",
				-- 	faded_red = "#fb4934",
				-- 	faded_green = "#b8bb26",
				-- 	faded_yellow = "#fabd2f",
				-- 	faded_blue = "#83a598",
				-- 	faded_purple = "#d3869b",
				-- 	faded_aqua = "#8ec07c",
				-- 	faded_orange = "#fe8019",
				-- 	dark_red_hard = "#fb4934",
				-- 	dark_red = "#fb4934",
				-- 	dark_red_soft = "#fb4934",
				-- 	light_red_hard = "#fb4934",
				-- 	light_red = "#fb4934",
				-- 	light_red_soft = "#fb4934",
				-- 	dark_green_hard = "#b8bb26",
				-- 	dark_green = "#b8bb26",
				-- 	dark_green_soft = "#b8bb26",
				-- 	light_green_hard = "#b8bb26",
				-- 	light_green = "#b8bb26",
				-- 	light_green_soft = "#b8bb26",
				-- 	dark_aqua_hard = "#8ec07c",
				-- 	dark_aqua = "#8ec07c",
				-- 	dark_aqua_soft = "#8ec07c",
				-- 	light_aqua_hard = "#8ec07c",
				-- 	light_aqua = "#8ec07c",
				-- 	light_aqua_soft = "#8ec07c",
				-- 	gray = "#d5c4a1",
			},
		})
		require("vim").cmd([[colorscheme gruvbox]])
	end,
	opts = ...,
}
